apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: myapp
    type: frontend
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.25.2
          ports:
            - containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      type: frontend