version: '3.1'
services:
  mysql:
    image: mysql
    secrets:                    # secrets block only for 'mysql' service
     - mysql_external_secret
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_external_secret
secrets:                        # top level secrets block
  mysql_external_secret:
    external: true
