#!/bin/bash

# Join the overlay network on the second host
docker swarm join-token worker
# Copy and run the command generated by the previous command on Host 2

# Create a service on Host 2 connected to the overlay network
docker service create --name service_on_host2 --network my_overlay_network nginx
